const {
  VITE_AWS_REGION,
  VITE_USER_POOL_ID,
  VITE_AMPLIFY_AUTH_IDENTITY_POOL_ID,
  VITE_APP_CLIENT_ID,
  VITE_APPSYNC_API_KEY,
  VITE_APPSYNC_ENDPOINT,
  VITE_LOCALSTACK_PORT,
  // @ts-ignore
} = import.meta.env

export const APP_URL = "http://localhost:3000"

export const AWS_REGION = VITE_AWS_REGION
export const USER_POOL_ID = VITE_USER_POOL_ID
export const AMPLIFY_AUTH_IDENTITY_POOL_ID = VITE_AMPLIFY_AUTH_IDENTITY_POOL_ID
export const APP_CLIENT_ID = VITE_APP_CLIENT_ID
export const APPSYNC_API_KEY = VITE_APPSYNC_API_KEY
export const APPSYNC_API_ENDPOINT = VITE_APPSYNC_ENDPOINT

// Localstack
export const LOCALSTACK_PORT = VITE_LOCALSTACK_PORT || "4566"
export const LOCALSTACK_ENDPOINT = `http://localhost:${LOCALSTACK_PORT}`
