export const ROOT_PATH = "/"
export const DOCS_PATH = "/docs"
export const SYSTEM_PATH = "/system"
export const APIGATEWAY_PATH = "/apigateway"
export const APPSYNC_PATH = "/appsync"
export const DYNAMODB_PATH = "/dynamodb"
export const RDS_PATH = "/rds"
export const MSK_PATH = "/msk"
