export const createDBInstanceCommandInput = {
  AllocatedStorage: 10,
  DBInstanceClass: "db.t3.small",
  DBName: "localstack-learning",
  DBInstanceIdentifier: "localstack-learning",
  Engine: "postgres",
  EngineVersion: "13.4",
  MasterUserPassword: "password",
  MasterUsername: "postgres",
  // AutoMinorVersionUpgrade
  // AvailabilityZone
  // BackupRetentionPeriod
  // BackupTarget
  // CharacterSetName
  // CopyTagsToSnapshot
  // CustomIamInstanceProfile
  // DBClusterIdentifier
  // DBParameterGroupName
  // DBSecurityGroups
  // DBSubnetGroupName
  // DeletionProtection
  // Domain
  // DomainIAMRoleName
  // EnableCloudwatchLogsExports
  // EnableCustomerOwnedIp
  // EnableIAMDatabaseAuthentication
  // EnablePerformanceInsights
  // Iops
  // KmsKeyId
  // LicenseModel
  // MaxAllocatedStorage
  // MonitoringInterval
  // MonitoringRoleArn
  // MultiAZ
  // NcharCharacterSetName
  // NetworkType
  // OptionGroupName
  // PerformanceInsightsKMSKeyId
  // PerformanceInsightsRetentionPeriod
  // Port
  // PreferredBackupWindow
  // PreferredMaintenanceWindow
  // ProcessorFeatures
  // PromotionTier
  // PubliclyAccessible
  // StorageEncrypted
  // StorageType
  // Tags
  // TdeCredentialArn
  // TdeCredentialPassword
  // Timezone
  // VpcSecurityGroupIds
}
